export const config = {
  name: 'Matias Valdez',
  email: 'matiasvaldez8184@gmail.com',
  social: {
    linkedin: 'https://www.linkedin.com/in/matiasvaldez1/',
    github: 'https://github.com/matiasvaldez1',
  },
  skills: [
    'React',
    'Next.js',
    'TypeScript',
    'Shopify',
    'Liquid',
    'Remix',
    'Node.js',
    'GraphQL',
    'tRPC',
    'Tailwind CSS',
    'PostgreSQL',
    'Prisma',
    'Docker',
    'Styled Components',
  ],
  experience: [
    { company: 'Limesharp', role: 'Shopify Front End Developer', period: 'Mar 2026 – Present' },
    { company: 'Prismfly', role: 'Shopify Frontend Developer', period: 'Oct 2025 – Jan 2026' },
    { company: 'ConversionFlow', role: 'Shopify Frontend Developer', period: 'Oct 2024 – Oct 2025' },
    { company: 'FJ Solutions', role: 'Shopify Frontend Developer', period: 'May 2024 – Dec 2024' },
    { company: 'GoHub', role: 'Full Stack Developer', period: 'May 2022 – May 2024' },
    { company: 'Coderhouse', role: 'Mentor', period: 'Jun 2022 – Oct 2022' },
  ],
  certifications: [
    'React: Testing and Debugging',
    'React: Design Patterns',
    'EFSET English Certificate C2',
  ],
}
